services:
  anmeraapistore:
    build:
      context: .
    container_name: anmeraApiStoreNuevo
    ports:
      - 3091:3091
    restart: always
    networks:
      - global_mi_red

networks:
  global_mi_red: